global: # Global configuration
  installCommand: paru -S --needed --noconfirm # Package install command, package name will be appended
  dotfiles: ~/dotfiles # Path to dotfiles, ~ will be expanded
variables: # Variables that will be replaced into parsed files
  background: 1E1E2E
  foreground: D9E0EE
  cursor: FAE3B0
  color0: 6E6C7E
  color8: 988BA2
  color1: F28FAD
  color9: F28FAD
  color2: ABE9B3
  color10: ABE9B3
  color3: FAE3B0
  color11: FAE3B0
  color4: 96CDFB
  color12: 96CDFB
  color5: DDB6F2
  color13: DDB6F2
  color6: F5C2E7
  color14: F5C2E7
  color7: C3BAC6
  color15: D9E0EE
modules: # List of modules
  yrice: {} # YRice can be used to manage itself
  foo: # Module name
    dirname: foo # dotfiles directory name. Default: module name
    enabled: true # if dotfiles needs to be managed. Default: true
    targetDir: ~/.config/foo # target configuration path. Default: XDG_CONFIG_DIR/{package_name} or ~/.config/{package name}
    packageName: foo # system package name. Default: None
    dependencies: [] # List of system dependencies. Default: []
    files: # List of files to be linked or parsed. Default: whole directory
      - source: bar.conf # file path
        target: bar.conf # target path of specific file in module targetPath
        parse: false # Whether this file needs to be parsed or not. Default: false
    preSteps: [] # List of custom commands to run before installing config
    postSteps: [] # List of custom commands to run after installing config
    requires: [] # List of other modules that need to be installed before
